# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Sample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomCollectionView
        pod 'AsyncDisplayKit', :git => 'https://github.com/facebook/AsyncDisplayKit.git', :tag => '2.0-beta.1'
end
