# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ASVerticalNestedCollectionNode' do

pod 'AsyncDisplayKit'

end

target 'ASVerticalNestedCollectionNodeTests' do

end

target 'ASVerticalNestedCollectionNodeUITests' do

end

