source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'ASAnimatedImage' do
	pod 'AsyncDisplayKit', :path => '../..'
	pod 'PINRemoteImage', :git => 'https://github.com/pinterest/PINRemoteImage.git', :branch => 'addPINAnimatedImage'
end

